### ISSUE TITLE
About the source code

### ISSUE THREAD

**Issue by dhx20150812** [sebastian-hofstaetter/tas-balanced-dense-retrieval#1]
Thanks for sharing this work. I'd like to re-implement your work?

So may I know when the source code will be open?

Thanks !

**Comment by sebastian-hofstaetter** [comment]
Hi,

Sorry about the delay - I am working on cleaning up the source & writing some guides for it. It will be available at the latest before SIGIR starts on the 11th of July.

Best,
Sebastian

**Comment by sebastian-hofstaetter** [comment]
Hi,

The source code is available now (including getting started guides) as part of our matchmaker library: https://github.com/sebastian-hofstaetter/matchmaker

If you have any questions, feel free to open an issue in the matchmaker repo. Thanks!

Best,
Sebastian
