### ISSUE TITLE
Early stopping set 

### ISSUE THREAD

**Issue by SunSiShining** [sebastian-hofstaetter/tas-balanced-dense-retrieval#2]
Thanks for your excellent work!

For section 4.3 of this paper, you mentioned a new early stop set. 
Could you share the early stop set (MS MARCO and TREC-DL) or creation script?

Looking forward to your reply : )

**Comment by sebastian-hofstaetter** [comment]
Hi,

I used this script https://github.com/sebastian-hofstaetter/matchmaker/blob/master/preprocessing/generate_smart_earlystopping_retrieval.py with the larger dev set of msmarco. Hope it helps!

Best,
Sebastian

**Comment by SunSiShining** [comment]
Thank you, Sebastian, for the prompt reply.
