### ISSUE TITLE
Why using faiss for clustering instead of k-means?

### ISSUE THREAD

**Issue by dli1** [sebastian-hofstaetter/tas-balanced-dense-retrieval#3]
In [query_clusterer.py](https://github.com/sebastian-hofstaetter/matchmaker/blob/master/matchmaker/distillation/query_clusterer.py), I notice you use faiss index to do query cluster. Is there any specific reason of doing so? How is it compared with k-mean clustering?

**Comment by sebastian-hofstaetter** [comment]
Hi,
As far as I am aware, this faiss method uses k-means under the hood to get the centroids and then we are grouping the queries based on the nearest centroid. We use faiss just for convenience, because we had most of the code already ready to go.
Best,
Sebastian

**Comment by dli1** [comment]
Thanks for clarifying it.
